// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: yaml.proto

package kubernetes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YamlData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Yaml string `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
}

func (x *YamlData) Reset() {
	*x = YamlData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaml_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YamlData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YamlData) ProtoMessage() {}

func (x *YamlData) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YamlData.ProtoReflect.Descriptor instead.
func (*YamlData) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{0}
}

func (x *YamlData) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

var File_yaml_proto protoreflect.FileDescriptor

var file_yaml_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x22, 0x1f, 0x0a, 0x09, 0x79, 0x61, 0x6d, 0x6c,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x77, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yaml_proto_rawDescOnce sync.Once
	file_yaml_proto_rawDescData = file_yaml_proto_rawDesc
)

func file_yaml_proto_rawDescGZIP() []byte {
	file_yaml_proto_rawDescOnce.Do(func() {
		file_yaml_proto_rawDescData = protoimpl.X.CompressGZIP(file_yaml_proto_rawDescData)
	})
	return file_yaml_proto_rawDescData
}

var file_yaml_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yaml_proto_goTypes = []interface{}{
	(*YamlData)(nil), // 0: kubernetes.yaml_data
}
var file_yaml_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yaml_proto_init() }
func file_yaml_proto_init() {
	if File_yaml_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yaml_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YamlData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yaml_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yaml_proto_goTypes,
		DependencyIndexes: file_yaml_proto_depIdxs,
		MessageInfos:      file_yaml_proto_msgTypes,
	}.Build()
	File_yaml_proto = out.File
	file_yaml_proto_rawDesc = nil
	file_yaml_proto_goTypes = nil
	file_yaml_proto_depIdxs = nil
}
