// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: k8s_namespace.proto

package servercomm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNamespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Namespace `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListNamespace) Reset() {
	*x = ListNamespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8s_namespace_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespace) ProtoMessage() {}

func (x *ListNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_k8s_namespace_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespace.ProtoReflect.Descriptor instead.
func (*ListNamespace) Descriptor() ([]byte, []int) {
	return file_k8s_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *ListNamespace) GetList() []*Namespace {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateNamespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source    *Namespace `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	NewSource *Namespace `protobuf:"bytes,2,opt,name=newSource,proto3" json:"newSource,omitempty"`
}

func (x *UpdateNamespace) Reset() {
	*x = UpdateNamespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8s_namespace_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNamespace) ProtoMessage() {}

func (x *UpdateNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_k8s_namespace_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNamespace.ProtoReflect.Descriptor instead.
func (*UpdateNamespace) Descriptor() ([]byte, []int) {
	return file_k8s_namespace_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateNamespace) GetSource() *Namespace {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *UpdateNamespace) GetNewSource() *Namespace {
	if x != nil {
		return x.NewSource
	}
	return nil
}

type Namespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8s_namespace_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_k8s_namespace_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_k8s_namespace_proto_rawDescGZIP(), []int{2}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_k8s_namespace_proto protoreflect.FileDescriptor

var file_k8s_namespace_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x38, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x33, 0x0a, 0x0e, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x66,
	0x0a, 0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x6e, 0x65, 0x77,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76,
	0x31, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x09, 0x6e, 0x65, 0x77,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x77, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_k8s_namespace_proto_rawDescOnce sync.Once
	file_k8s_namespace_proto_rawDescData = file_k8s_namespace_proto_rawDesc
)

func file_k8s_namespace_proto_rawDescGZIP() []byte {
	file_k8s_namespace_proto_rawDescOnce.Do(func() {
		file_k8s_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(file_k8s_namespace_proto_rawDescData)
	})
	return file_k8s_namespace_proto_rawDescData
}

var file_k8s_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_k8s_namespace_proto_goTypes = []interface{}{
	(*ListNamespace)(nil),   // 0: v1.list_namespace
	(*UpdateNamespace)(nil), // 1: v1.update_namespace
	(*Namespace)(nil),       // 2: v1.namespace
}
var file_k8s_namespace_proto_depIdxs = []int32{
	2, // 0: v1.list_namespace.list:type_name -> v1.namespace
	2, // 1: v1.update_namespace.source:type_name -> v1.namespace
	2, // 2: v1.update_namespace.newSource:type_name -> v1.namespace
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_k8s_namespace_proto_init() }
func file_k8s_namespace_proto_init() {
	if File_k8s_namespace_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_k8s_namespace_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNamespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8s_namespace_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNamespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8s_namespace_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_k8s_namespace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_k8s_namespace_proto_goTypes,
		DependencyIndexes: file_k8s_namespace_proto_depIdxs,
		MessageInfos:      file_k8s_namespace_proto_msgTypes,
	}.Build()
	File_k8s_namespace_proto = out.File
	file_k8s_namespace_proto_rawDesc = nil
	file_k8s_namespace_proto_goTypes = nil
	file_k8s_namespace_proto_depIdxs = nil
}
