//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: loginToken.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `V1_TokenClient`, then call methods of this protocol to make API calls.
public protocol V1_TokenClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: V1_TokenClientInterceptorFactoryProtocol? { get }

  func createRegisterToken(
    _ request: V1_Void,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Void, V1_TokenMessage>

  func createRefreshToken(
    _ request: V1_CreateRefreshTokenMessage,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_CreateRefreshTokenMessage, V1_TokenMessage>

  func readRefreshToken(
    _ request: V1_Void,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Void, V1_RefreshTokenList>

  func updatehRefreshToken(
    _ request: V1_Uuid,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Uuid, V1_TokenMessage>

  func deleteRefreshToken(
    _ request: V1_Uuid,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Uuid, V1_DeleteRefreshTokenMessage>

  func createAccessToken(
    _ request: V1_Uuid,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Uuid, V1_TokenMessage>
}

extension V1_TokenClientProtocol {
  public var serviceName: String {
    return "v1.Token"
  }

  /// Unary call to CreateRegisterToken
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateRegisterToken.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createRegisterToken(
    _ request: V1_Void,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Void, V1_TokenMessage> {
    return self.makeUnaryCall(
      path: "/v1.Token/CreateRegisterToken",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateRegisterTokenInterceptors() ?? []
    )
  }

  /// Unary call to CreateRefreshToken
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateRefreshToken.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createRefreshToken(
    _ request: V1_CreateRefreshTokenMessage,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_CreateRefreshTokenMessage, V1_TokenMessage> {
    return self.makeUnaryCall(
      path: "/v1.Token/CreateRefreshToken",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateRefreshTokenInterceptors() ?? []
    )
  }

  /// Needs, Authorization
  ///
  /// - Parameters:
  ///   - request: Request to send to ReadRefreshToken.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func readRefreshToken(
    _ request: V1_Void,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Void, V1_RefreshTokenList> {
    return self.makeUnaryCall(
      path: "/v1.Token/ReadRefreshToken",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReadRefreshTokenInterceptors() ?? []
    )
  }

  /// Needs, Authorization
  /// Uuid : Refreshtoken Uuid
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdatehRefreshToken.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updatehRefreshToken(
    _ request: V1_Uuid,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Uuid, V1_TokenMessage> {
    return self.makeUnaryCall(
      path: "/v1.Token/UpdatehRefreshToken",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatehRefreshTokenInterceptors() ?? []
    )
  }

  /// Needs, Authorization
  /// Uuid : Refreshtoken Uuid
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteRefreshToken.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func deleteRefreshToken(
    _ request: V1_Uuid,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Uuid, V1_DeleteRefreshTokenMessage> {
    return self.makeUnaryCall(
      path: "/v1.Token/DeleteRefreshToken",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteRefreshTokenInterceptors() ?? []
    )
  }

  /// Needs, Authorization
  /// Uuid : Refreshtoken Uuid
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateAccessToken.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createAccessToken(
    _ request: V1_Uuid,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Uuid, V1_TokenMessage> {
    return self.makeUnaryCall(
      path: "/v1.Token/CreateAccessToken",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccessTokenInterceptors() ?? []
    )
  }
}

public protocol V1_TokenClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'createRegisterToken'.
  func makeCreateRegisterTokenInterceptors() -> [ClientInterceptor<V1_Void, V1_TokenMessage>]

  /// - Returns: Interceptors to use when invoking 'createRefreshToken'.
  func makeCreateRefreshTokenInterceptors() -> [ClientInterceptor<V1_CreateRefreshTokenMessage, V1_TokenMessage>]

  /// - Returns: Interceptors to use when invoking 'readRefreshToken'.
  func makeReadRefreshTokenInterceptors() -> [ClientInterceptor<V1_Void, V1_RefreshTokenList>]

  /// - Returns: Interceptors to use when invoking 'updatehRefreshToken'.
  func makeUpdatehRefreshTokenInterceptors() -> [ClientInterceptor<V1_Uuid, V1_TokenMessage>]

  /// - Returns: Interceptors to use when invoking 'deleteRefreshToken'.
  func makeDeleteRefreshTokenInterceptors() -> [ClientInterceptor<V1_Uuid, V1_DeleteRefreshTokenMessage>]

  /// - Returns: Interceptors to use when invoking 'createAccessToken'.
  func makeCreateAccessTokenInterceptors() -> [ClientInterceptor<V1_Uuid, V1_TokenMessage>]
}

public final class V1_TokenClient: V1_TokenClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: V1_TokenClientInterceptorFactoryProtocol?

  /// Creates a client for the v1.Token service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: V1_TokenClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol V1_TokenProvider: CallHandlerProvider {
  var interceptors: V1_TokenServerInterceptorFactoryProtocol? { get }

  func createRegisterToken(request: V1_Void, context: StatusOnlyCallContext) -> EventLoopFuture<V1_TokenMessage>

  func createRefreshToken(request: V1_CreateRefreshTokenMessage, context: StatusOnlyCallContext) -> EventLoopFuture<V1_TokenMessage>

  /// Needs, Authorization
  func readRefreshToken(request: V1_Void, context: StatusOnlyCallContext) -> EventLoopFuture<V1_RefreshTokenList>

  /// Needs, Authorization
  /// Uuid : Refreshtoken Uuid
  func updatehRefreshToken(request: V1_Uuid, context: StatusOnlyCallContext) -> EventLoopFuture<V1_TokenMessage>

  /// Needs, Authorization
  /// Uuid : Refreshtoken Uuid
  func deleteRefreshToken(request: V1_Uuid, context: StatusOnlyCallContext) -> EventLoopFuture<V1_DeleteRefreshTokenMessage>

  /// Needs, Authorization
  /// Uuid : Refreshtoken Uuid
  func createAccessToken(request: V1_Uuid, context: StatusOnlyCallContext) -> EventLoopFuture<V1_TokenMessage>
}

extension V1_TokenProvider {
  public var serviceName: Substring { return "v1.Token" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateRegisterToken":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Void>(),
        responseSerializer: ProtobufSerializer<V1_TokenMessage>(),
        interceptors: self.interceptors?.makeCreateRegisterTokenInterceptors() ?? [],
        userFunction: self.createRegisterToken(request:context:)
      )

    case "CreateRefreshToken":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_CreateRefreshTokenMessage>(),
        responseSerializer: ProtobufSerializer<V1_TokenMessage>(),
        interceptors: self.interceptors?.makeCreateRefreshTokenInterceptors() ?? [],
        userFunction: self.createRefreshToken(request:context:)
      )

    case "ReadRefreshToken":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Void>(),
        responseSerializer: ProtobufSerializer<V1_RefreshTokenList>(),
        interceptors: self.interceptors?.makeReadRefreshTokenInterceptors() ?? [],
        userFunction: self.readRefreshToken(request:context:)
      )

    case "UpdatehRefreshToken":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Uuid>(),
        responseSerializer: ProtobufSerializer<V1_TokenMessage>(),
        interceptors: self.interceptors?.makeUpdatehRefreshTokenInterceptors() ?? [],
        userFunction: self.updatehRefreshToken(request:context:)
      )

    case "DeleteRefreshToken":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Uuid>(),
        responseSerializer: ProtobufSerializer<V1_DeleteRefreshTokenMessage>(),
        interceptors: self.interceptors?.makeDeleteRefreshTokenInterceptors() ?? [],
        userFunction: self.deleteRefreshToken(request:context:)
      )

    case "CreateAccessToken":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Uuid>(),
        responseSerializer: ProtobufSerializer<V1_TokenMessage>(),
        interceptors: self.interceptors?.makeCreateAccessTokenInterceptors() ?? [],
        userFunction: self.createAccessToken(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol V1_TokenServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'createRegisterToken'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateRegisterTokenInterceptors() -> [ServerInterceptor<V1_Void, V1_TokenMessage>]

  /// - Returns: Interceptors to use when handling 'createRefreshToken'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateRefreshTokenInterceptors() -> [ServerInterceptor<V1_CreateRefreshTokenMessage, V1_TokenMessage>]

  /// - Returns: Interceptors to use when handling 'readRefreshToken'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeReadRefreshTokenInterceptors() -> [ServerInterceptor<V1_Void, V1_RefreshTokenList>]

  /// - Returns: Interceptors to use when handling 'updatehRefreshToken'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdatehRefreshTokenInterceptors() -> [ServerInterceptor<V1_Uuid, V1_TokenMessage>]

  /// - Returns: Interceptors to use when handling 'deleteRefreshToken'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteRefreshTokenInterceptors() -> [ServerInterceptor<V1_Uuid, V1_DeleteRefreshTokenMessage>]

  /// - Returns: Interceptors to use when handling 'createAccessToken'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateAccessTokenInterceptors() -> [ServerInterceptor<V1_Uuid, V1_TokenMessage>]
}
