//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: user.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `V1_UserAccountClient`, then call methods of this protocol to make API calls.
internal protocol V1_UserAccountClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: V1_UserAccountClientInterceptorFactoryProtocol? { get }

  func createUser(
    _ request: V1_MakeUser,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_MakeUser, V1_Result>

  func readUser(
    _ request: V1_Uuid,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Uuid, V1_UserDetail>

  func updateUser(
    _ request: V1_User,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_User, V1_Result>

  func deleteUser(
    _ request: V1_Uuid,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Uuid, V1_Result>
}

extension V1_UserAccountClientProtocol {
  internal var serviceName: String {
    return "v1.UserAccount"
  }

  /// Unary call to CreateUser
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createUser(
    _ request: V1_MakeUser,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_MakeUser, V1_Result> {
    return self.makeUnaryCall(
      path: "/v1.UserAccount/CreateUser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateUserInterceptors() ?? []
    )
  }

  /// Unary call to ReadUser
  ///
  /// - Parameters:
  ///   - request: Request to send to ReadUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func readUser(
    _ request: V1_Uuid,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Uuid, V1_UserDetail> {
    return self.makeUnaryCall(
      path: "/v1.UserAccount/ReadUser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReadUserInterceptors() ?? []
    )
  }

  /// Unary call to UpdateUser
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateUser(
    _ request: V1_User,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_User, V1_Result> {
    return self.makeUnaryCall(
      path: "/v1.UserAccount/UpdateUser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateUserInterceptors() ?? []
    )
  }

  /// Unary call to DeleteUser
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteUser(
    _ request: V1_Uuid,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Uuid, V1_Result> {
    return self.makeUnaryCall(
      path: "/v1.UserAccount/DeleteUser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteUserInterceptors() ?? []
    )
  }
}

internal protocol V1_UserAccountClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'createUser'.
  func makeCreateUserInterceptors() -> [ClientInterceptor<V1_MakeUser, V1_Result>]

  /// - Returns: Interceptors to use when invoking 'readUser'.
  func makeReadUserInterceptors() -> [ClientInterceptor<V1_Uuid, V1_UserDetail>]

  /// - Returns: Interceptors to use when invoking 'updateUser'.
  func makeUpdateUserInterceptors() -> [ClientInterceptor<V1_User, V1_Result>]

  /// - Returns: Interceptors to use when invoking 'deleteUser'.
  func makeDeleteUserInterceptors() -> [ClientInterceptor<V1_Uuid, V1_Result>]
}

internal final class V1_UserAccountClient: V1_UserAccountClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: V1_UserAccountClientInterceptorFactoryProtocol?

  /// Creates a client for the v1.UserAccount service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: V1_UserAccountClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Usage: instantiate `V1_OrganizationAccountClient`, then call methods of this protocol to make API calls.
internal protocol V1_OrganizationAccountClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: V1_OrganizationAccountClientInterceptorFactoryProtocol? { get }

  func createOrganization(
    _ request: V1_MakeOrganization,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_MakeOrganization, V1_Result>

  func readOrganization(
    _ request: V1_Uuid,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Uuid, V1_OrganizationDetail>

  func updateOrganization(
    _ request: V1_Uuid,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Uuid, V1_Result>

  func deleteOrganization(
    _ request: V1_Uuid,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Uuid, V1_Result>

  func appendUser(
    _ request: V1_Uuid,
    callOptions: CallOptions?
  ) -> UnaryCall<V1_Uuid, V1_OrganizationDetail>
}

extension V1_OrganizationAccountClientProtocol {
  internal var serviceName: String {
    return "v1.OrganizationAccount"
  }

  /// Unary call to CreateOrganization
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateOrganization.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createOrganization(
    _ request: V1_MakeOrganization,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_MakeOrganization, V1_Result> {
    return self.makeUnaryCall(
      path: "/v1.OrganizationAccount/CreateOrganization",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateOrganizationInterceptors() ?? []
    )
  }

  /// Unary call to ReadOrganization
  ///
  /// - Parameters:
  ///   - request: Request to send to ReadOrganization.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func readOrganization(
    _ request: V1_Uuid,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Uuid, V1_OrganizationDetail> {
    return self.makeUnaryCall(
      path: "/v1.OrganizationAccount/ReadOrganization",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReadOrganizationInterceptors() ?? []
    )
  }

  /// Unary call to UpdateOrganization
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateOrganization.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateOrganization(
    _ request: V1_Uuid,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Uuid, V1_Result> {
    return self.makeUnaryCall(
      path: "/v1.OrganizationAccount/UpdateOrganization",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateOrganizationInterceptors() ?? []
    )
  }

  /// Unary call to DeleteOrganization
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteOrganization.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteOrganization(
    _ request: V1_Uuid,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Uuid, V1_Result> {
    return self.makeUnaryCall(
      path: "/v1.OrganizationAccount/DeleteOrganization",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteOrganizationInterceptors() ?? []
    )
  }

  /// Unary call to AppendUser
  ///
  /// - Parameters:
  ///   - request: Request to send to AppendUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func appendUser(
    _ request: V1_Uuid,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<V1_Uuid, V1_OrganizationDetail> {
    return self.makeUnaryCall(
      path: "/v1.OrganizationAccount/AppendUser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAppendUserInterceptors() ?? []
    )
  }
}

internal protocol V1_OrganizationAccountClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'createOrganization'.
  func makeCreateOrganizationInterceptors() -> [ClientInterceptor<V1_MakeOrganization, V1_Result>]

  /// - Returns: Interceptors to use when invoking 'readOrganization'.
  func makeReadOrganizationInterceptors() -> [ClientInterceptor<V1_Uuid, V1_OrganizationDetail>]

  /// - Returns: Interceptors to use when invoking 'updateOrganization'.
  func makeUpdateOrganizationInterceptors() -> [ClientInterceptor<V1_Uuid, V1_Result>]

  /// - Returns: Interceptors to use when invoking 'deleteOrganization'.
  func makeDeleteOrganizationInterceptors() -> [ClientInterceptor<V1_Uuid, V1_Result>]

  /// - Returns: Interceptors to use when invoking 'appendUser'.
  func makeAppendUserInterceptors() -> [ClientInterceptor<V1_Uuid, V1_OrganizationDetail>]
}

internal final class V1_OrganizationAccountClient: V1_OrganizationAccountClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: V1_OrganizationAccountClientInterceptorFactoryProtocol?

  /// Creates a client for the v1.OrganizationAccount service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: V1_OrganizationAccountClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol V1_UserAccountProvider: CallHandlerProvider {
  var interceptors: V1_UserAccountServerInterceptorFactoryProtocol? { get }

  func createUser(request: V1_MakeUser, context: StatusOnlyCallContext) -> EventLoopFuture<V1_Result>

  func readUser(request: V1_Uuid, context: StatusOnlyCallContext) -> EventLoopFuture<V1_UserDetail>

  func updateUser(request: V1_User, context: StatusOnlyCallContext) -> EventLoopFuture<V1_Result>

  func deleteUser(request: V1_Uuid, context: StatusOnlyCallContext) -> EventLoopFuture<V1_Result>
}

extension V1_UserAccountProvider {
  internal var serviceName: Substring { return "v1.UserAccount" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateUser":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_MakeUser>(),
        responseSerializer: ProtobufSerializer<V1_Result>(),
        interceptors: self.interceptors?.makeCreateUserInterceptors() ?? [],
        userFunction: self.createUser(request:context:)
      )

    case "ReadUser":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Uuid>(),
        responseSerializer: ProtobufSerializer<V1_UserDetail>(),
        interceptors: self.interceptors?.makeReadUserInterceptors() ?? [],
        userFunction: self.readUser(request:context:)
      )

    case "UpdateUser":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_User>(),
        responseSerializer: ProtobufSerializer<V1_Result>(),
        interceptors: self.interceptors?.makeUpdateUserInterceptors() ?? [],
        userFunction: self.updateUser(request:context:)
      )

    case "DeleteUser":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Uuid>(),
        responseSerializer: ProtobufSerializer<V1_Result>(),
        interceptors: self.interceptors?.makeDeleteUserInterceptors() ?? [],
        userFunction: self.deleteUser(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol V1_UserAccountServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'createUser'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateUserInterceptors() -> [ServerInterceptor<V1_MakeUser, V1_Result>]

  /// - Returns: Interceptors to use when handling 'readUser'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeReadUserInterceptors() -> [ServerInterceptor<V1_Uuid, V1_UserDetail>]

  /// - Returns: Interceptors to use when handling 'updateUser'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateUserInterceptors() -> [ServerInterceptor<V1_User, V1_Result>]

  /// - Returns: Interceptors to use when handling 'deleteUser'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteUserInterceptors() -> [ServerInterceptor<V1_Uuid, V1_Result>]
}
/// To build a server, implement a class that conforms to this protocol.
internal protocol V1_OrganizationAccountProvider: CallHandlerProvider {
  var interceptors: V1_OrganizationAccountServerInterceptorFactoryProtocol? { get }

  func createOrganization(request: V1_MakeOrganization, context: StatusOnlyCallContext) -> EventLoopFuture<V1_Result>

  func readOrganization(request: V1_Uuid, context: StatusOnlyCallContext) -> EventLoopFuture<V1_OrganizationDetail>

  func updateOrganization(request: V1_Uuid, context: StatusOnlyCallContext) -> EventLoopFuture<V1_Result>

  func deleteOrganization(request: V1_Uuid, context: StatusOnlyCallContext) -> EventLoopFuture<V1_Result>

  func appendUser(request: V1_Uuid, context: StatusOnlyCallContext) -> EventLoopFuture<V1_OrganizationDetail>
}

extension V1_OrganizationAccountProvider {
  internal var serviceName: Substring { return "v1.OrganizationAccount" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateOrganization":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_MakeOrganization>(),
        responseSerializer: ProtobufSerializer<V1_Result>(),
        interceptors: self.interceptors?.makeCreateOrganizationInterceptors() ?? [],
        userFunction: self.createOrganization(request:context:)
      )

    case "ReadOrganization":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Uuid>(),
        responseSerializer: ProtobufSerializer<V1_OrganizationDetail>(),
        interceptors: self.interceptors?.makeReadOrganizationInterceptors() ?? [],
        userFunction: self.readOrganization(request:context:)
      )

    case "UpdateOrganization":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Uuid>(),
        responseSerializer: ProtobufSerializer<V1_Result>(),
        interceptors: self.interceptors?.makeUpdateOrganizationInterceptors() ?? [],
        userFunction: self.updateOrganization(request:context:)
      )

    case "DeleteOrganization":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Uuid>(),
        responseSerializer: ProtobufSerializer<V1_Result>(),
        interceptors: self.interceptors?.makeDeleteOrganizationInterceptors() ?? [],
        userFunction: self.deleteOrganization(request:context:)
      )

    case "AppendUser":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<V1_Uuid>(),
        responseSerializer: ProtobufSerializer<V1_OrganizationDetail>(),
        interceptors: self.interceptors?.makeAppendUserInterceptors() ?? [],
        userFunction: self.appendUser(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol V1_OrganizationAccountServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'createOrganization'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateOrganizationInterceptors() -> [ServerInterceptor<V1_MakeOrganization, V1_Result>]

  /// - Returns: Interceptors to use when handling 'readOrganization'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeReadOrganizationInterceptors() -> [ServerInterceptor<V1_Uuid, V1_OrganizationDetail>]

  /// - Returns: Interceptors to use when handling 'updateOrganization'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateOrganizationInterceptors() -> [ServerInterceptor<V1_Uuid, V1_Result>]

  /// - Returns: Interceptors to use when handling 'deleteOrganization'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteOrganizationInterceptors() -> [ServerInterceptor<V1_Uuid, V1_Result>]

  /// - Returns: Interceptors to use when handling 'appendUser'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAppendUserInterceptors() -> [ServerInterceptor<V1_Uuid, V1_OrganizationDetail>]
}
