# This is a basic workflow to help you get started with Actions

name: Go-Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          
      - name: Run scripts
        run: |
          mkdir ../test
          cp -R ./protos/v1/ ../test
          cd ../test/v1
          
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          export PATH="$PATH:$HOME/go/bin"
          
          cd kubernetes
          for file in *.proto
          do
            protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative -I . "$file"
          	echo "WORK : [$file]"
          done
          cd ../servercomm
          for file in *.proto
          do
            protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative -I . "$file"
          	echo "WORK : [$file]"
          done
          
          cd ..
          find . -name "*.proto" -delete
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: "release-v1-go"
          clean: true
        
      - name: copy
        run: |
          find . -name "*.go" -delete
          pwd
          ls
          cp -r -f ../test/v1 .
    
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: '.'
          ref: "release-v1-go"
          author_name: 'Piorosen-Bot'
          author_email: 'ckwngud1@gmail.com'
          message: "[BOT] ${{ github.event.head_commit.message }}"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    
    # BOT TOKEN인뎅..?
      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          branch: "release-v1-go"
          
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: "release-v1-go"
